#!/usr/bin/env python3
"""Create sample deals for demonstration."""

import sys
from pathlib import Path
from datetime import datetime, timedelta

sys.path.insert(0, str(Path(__file__).parent.parent))

from backend.models import Deal, DealStatus
from backend.deals_store import save_deals

# Create sample deals with good images for multiple categories
sample_deals = [
    # Electronics
    Deal(
        id='sample_cb_1',
        title='Apple AirPods Pro 2e generatie met MagSafe',
        description='Actieve ruisonderdrukking met H2-chip. Tot 6 uur luistertijd.',
        merchant='Coolblue',
        merchant_logo='https://logo.clearbit.com/coolblue.nl',
        original_price=299.00,
        sale_price=249.00,
        discount_percentage=17,
        coupon_code=None,
        affiliate_url='https://www.coolblue.nl/product/906486/apple-airpods-pro-2e-generatie-met-magsafe.html',
        category='electronics',
        image_url='https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=7),
        source='coolblue',
        source_url='https://www.coolblue.nl/acties',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_mm_1',
        title='Samsung 65" QLED 4K Smart TV',
        description='Crystal UHD processor voor scherpe beelden. Smart TV met apps.',
        merchant='MediaMarkt',
        merchant_logo='https://logo.clearbit.com/mediamarkt.nl',
        original_price=899.00,
        sale_price=699.00,
        discount_percentage=22,
        coupon_code=None,
        affiliate_url='https://www.mediamarkt.nl/',
        category='electronics',
        image_url='https://images.unsplash.com/photo-1593784991095-a205069470b6?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=5),
        source='mediamarkt',
        source_url='https://www.mediamarkt.nl/aanbiedingen',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_bol_1',
        title='Sony WH-1000XM5 Koptelefoon',
        description='Premium noise-cancelling koptelefoon. 30 uur batterijduur.',
        merchant='Bol.com',
        merchant_logo='https://logo.clearbit.com/bol.com',
        original_price=379.00,
        sale_price=299.00,
        discount_percentage=21,
        coupon_code=None,
        affiliate_url='https://www.bol.com/',
        category='electronics',
        image_url='https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=6),
        source='bol',
        source_url='https://www.bol.com/aanbiedingen',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_bol_2',
        title='Nintendo Switch OLED Model',
        description='7-inch OLED scherm. 64GB opslag. Inclusief Joy-Con.',
        merchant='Bol.com',
        merchant_logo='https://logo.clearbit.com/bol.com',
        original_price=369.99,
        sale_price=319.99,
        discount_percentage=14,
        coupon_code=None,
        affiliate_url='https://www.bol.com/',
        category='electronics',
        image_url='https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=5),
        source='bol',
        source_url='https://www.bol.com/aanbiedingen',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_ibood_1',
        title='Philips Hue Starterkit E27',
        description='3 slimme lampen + bridge. Miljoenen kleuren. App-bediening.',
        merchant='iBOOD',
        merchant_logo='https://logo.clearbit.com/ibood.com',
        original_price=149.95,
        sale_price=99.95,
        discount_percentage=33,
        coupon_code=None,
        affiliate_url='https://www.ibood.com/',
        category='electronics',
        image_url='https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=2),
        source='ibood',
        source_url='https://www.ibood.com/nl/nl/',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    # Fashion
    Deal(
        id='sample_zal_1',
        title='Nike Air Max 90 Sneakers',
        description='Iconische sneakers met Air-demping. Klassiek design.',
        merchant='Zalando',
        merchant_logo='https://logo.clearbit.com/zalando.nl',
        original_price=149.99,
        sale_price=99.99,
        discount_percentage=33,
        coupon_code=None,
        affiliate_url='https://www.zalando.nl/',
        category='fashion',
        image_url='https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=7),
        source='zalando',
        source_url='https://www.zalando.nl/sale',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_wk_1',
        title='Levi\'s 501 Original Jeans',
        description='De originele jeans. Straight fit, klassieke look.',
        merchant='Wehkamp',
        merchant_logo='https://logo.clearbit.com/wehkamp.nl',
        original_price=109.95,
        sale_price=69.95,
        discount_percentage=36,
        coupon_code=None,
        affiliate_url='https://www.wehkamp.nl/',
        category='fashion',
        image_url='https://images.unsplash.com/photo-1542272604-787c3835535d?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=5),
        source='wehkamp',
        source_url='https://www.wehkamp.nl/sale',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_hm_1',
        title='H&M Premium Winterjas Heren',
        description='Warme gewatteerde jas. Waterafstotend. Zwart.',
        merchant='H&M',
        merchant_logo='https://logo.clearbit.com/hm.com',
        original_price=129.99,
        sale_price=79.99,
        discount_percentage=38,
        coupon_code=None,
        affiliate_url='https://www.hm.com/nl/',
        category='fashion',
        image_url='https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=14),
        source='hm',
        source_url='https://www.hm.com/nl/sale',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_ay_1',
        title='Adidas Originals Hoodie',
        description='Klassieke hoodie met trefoil logo. 100% katoen.',
        merchant='About You',
        merchant_logo='https://logo.clearbit.com/aboutyou.nl',
        original_price=79.95,
        sale_price=49.95,
        discount_percentage=38,
        coupon_code=None,
        affiliate_url='https://www.aboutyou.nl/',
        category='fashion',
        image_url='https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=7),
        source='aboutyou',
        source_url='https://www.aboutyou.nl/sale',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_zal_2',
        title='BOSS Dames Tas Zwart Leer',
        description='Elegante leren handtas. Luxe afwerking. Verstelbare riem.',
        merchant='Zalando',
        merchant_logo='https://logo.clearbit.com/zalando.nl',
        original_price=299.00,
        sale_price=179.00,
        discount_percentage=40,
        coupon_code=None,
        affiliate_url='https://www.zalando.nl/',
        category='fashion',
        image_url='https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=10),
        source='zalando',
        source_url='https://www.zalando.nl/sale',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    # Home
    Deal(
        id='sample_ikea_1',
        title='MALM Bed 180x200 wit',
        description='Strak design, veel opbergruimte onder het bed.',
        merchant='IKEA',
        merchant_logo='https://logo.clearbit.com/ikea.com',
        original_price=299.00,
        sale_price=229.00,
        discount_percentage=23,
        coupon_code=None,
        affiliate_url='https://www.ikea.com/nl/',
        category='home',
        image_url='https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=14),
        source='ikea',
        source_url='https://www.ikea.com/nl/nl/offers',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_action_1',
        title='LED Bureaulamp met Dimmer',
        description='Verstelbare arm. 3 lichtstanden. USB-oplaadpoort.',
        merchant='Action',
        merchant_logo='https://logo.clearbit.com/action.com',
        original_price=14.95,
        sale_price=9.95,
        discount_percentage=33,
        coupon_code=None,
        affiliate_url='https://www.action.com/',
        category='home',
        image_url='https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=7),
        source='action',
        source_url='https://www.action.com/nl-nl/aanbiedingen/',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_gamma_1',
        title='Bosch Accuboormachine 18V',
        description='Inclusief 2 accu\'s en lader. 50-delige bitset.',
        merchant='GAMMA',
        merchant_logo='https://logo.clearbit.com/gamma.nl',
        original_price=179.00,
        sale_price=129.00,
        discount_percentage=28,
        coupon_code=None,
        affiliate_url='https://www.gamma.nl/',
        category='home',
        image_url='https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=10),
        source='gamma',
        source_url='https://www.gamma.nl/aanbiedingen',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_fonq_1',
        title='Zuiver Dusk Fauteuil',
        description='Retro design. Fluwelen bekleding. Grijs.',
        merchant='Fonq',
        merchant_logo='https://logo.clearbit.com/fonq.nl',
        original_price=449.00,
        sale_price=299.00,
        discount_percentage=33,
        coupon_code=None,
        affiliate_url='https://www.fonq.nl/',
        category='home',
        image_url='https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=14),
        source='fonq',
        source_url='https://www.fonq.nl/sale',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_praxis_1',
        title='Karcher Hogedrukreiniger K3',
        description='115 bar druk. Inclusief terrasreiniger en schuimlans.',
        merchant='Praxis',
        merchant_logo='https://logo.clearbit.com/praxis.nl',
        original_price=199.00,
        sale_price=149.00,
        discount_percentage=25,
        coupon_code=None,
        affiliate_url='https://www.praxis.nl/',
        category='home',
        image_url='https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=7),
        source='praxis',
        source_url='https://www.praxis.nl/aanbiedingen',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    # Beauty
    Deal(
        id='sample_kr_1',
        title='L\'Oreal Paris Elvive Shampoo 3-pack',
        description='Verzorgende shampoo voor beschadigd haar. 3x 250ml.',
        merchant='Kruidvat',
        merchant_logo='https://logo.clearbit.com/kruidvat.nl',
        original_price=14.97,
        sale_price=8.99,
        discount_percentage=40,
        coupon_code=None,
        affiliate_url='https://www.kruidvat.nl/',
        category='beauty',
        image_url='https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=7),
        source='kruidvat',
        source_url='https://www.kruidvat.nl/aanbiedingen',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_douglas_1',
        title='Dior Sauvage Eau de Parfum 100ml',
        description='Iconisch herenparfum. Krachtig en fris.',
        merchant='Douglas',
        merchant_logo='https://logo.clearbit.com/douglas.nl',
        original_price=125.00,
        sale_price=89.95,
        discount_percentage=28,
        coupon_code=None,
        affiliate_url='https://www.douglas.nl/',
        category='beauty',
        image_url='https://images.unsplash.com/photo-1541643600914-78b084683601?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=7),
        source='douglas',
        source_url='https://www.douglas.nl/sale',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_etos_1',
        title='Gillette Fusion5 Scheermesjes 12-pack',
        description='Precision trimmer. FlexBall technologie.',
        merchant='Etos',
        merchant_logo='https://logo.clearbit.com/etos.nl',
        original_price=39.99,
        sale_price=24.99,
        discount_percentage=38,
        coupon_code=None,
        affiliate_url='https://www.etos.nl/',
        category='beauty',
        image_url='https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=5),
        source='etos',
        source_url='https://www.etos.nl/aanbiedingen',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_rituals_1',
        title='Rituals The Ritual of Sakura Giftset',
        description='Luxe geschenkset. Body cream, scrub en schuimbad.',
        merchant='Rituals',
        merchant_logo='https://logo.clearbit.com/rituals.com',
        original_price=49.90,
        sale_price=34.90,
        discount_percentage=30,
        coupon_code=None,
        affiliate_url='https://www.rituals.com/',
        category='beauty',
        image_url='https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=10),
        source='rituals',
        source_url='https://www.rituals.com/sale',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_parfums_1',
        title='Chanel No 5 Eau de Parfum 50ml',
        description='Tijdloos damesparfum. Bloemig en elegant.',
        merchant='Parfumswinkel',
        merchant_logo='https://logo.clearbit.com/parfumswinkel.nl',
        original_price=139.00,
        sale_price=99.00,
        discount_percentage=29,
        coupon_code=None,
        affiliate_url='https://www.parfumswinkel.nl/',
        category='beauty',
        image_url='https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=14),
        source='parfumswinkel',
        source_url='https://www.parfumswinkel.nl/sale',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    # Sports
    Deal(
        id='sample_dec_1',
        title='Decathlon Mountainbike 27.5"',
        description='Perfect voor beginners. 21 versnellingen, schijfremmen.',
        merchant='Decathlon',
        merchant_logo='https://logo.clearbit.com/decathlon.nl',
        original_price=349.00,
        sale_price=269.00,
        discount_percentage=23,
        coupon_code=None,
        affiliate_url='https://www.decathlon.nl/',
        category='sports',
        image_url='https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=10),
        source='decathlon',
        source_url='https://www.decathlon.nl/sale',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_int_1',
        title='Adidas Predator Voetbalschoenen',
        description='Professionele voetbalschoenen. FG noppen. Rood/zwart.',
        merchant='Intersport',
        merchant_logo='https://logo.clearbit.com/intersport.nl',
        original_price=179.99,
        sale_price=119.99,
        discount_percentage=33,
        coupon_code=None,
        affiliate_url='https://www.intersport.nl/',
        category='sports',
        image_url='https://images.unsplash.com/photo-1511886929837-354d827aae26?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=7),
        source='intersport',
        source_url='https://www.intersport.nl/sale',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_perry_1',
        title='Nike Dri-FIT Trainingsset Heren',
        description='Shirt en korte broek. Ademend materiaal.',
        merchant='Perry Sport',
        merchant_logo='https://logo.clearbit.com/perrysport.nl',
        original_price=89.99,
        sale_price=54.99,
        discount_percentage=39,
        coupon_code=None,
        affiliate_url='https://www.perrysport.nl/',
        category='sports',
        image_url='https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=5),
        source='perrysport',
        source_url='https://www.perrysport.nl/sale',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_sd_1',
        title='Under Armour Sporttas Groot',
        description='55 liter capaciteit. Schoenencompartiment. Zwart.',
        merchant='Sport Direct',
        merchant_logo='https://logo.clearbit.com/sportsdirect.com',
        original_price=59.99,
        sale_price=34.99,
        discount_percentage=42,
        coupon_code=None,
        affiliate_url='https://nl.sportsdirect.com/',
        category='sports',
        image_url='https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=10),
        source='sportdirect',
        source_url='https://nl.sportsdirect.com/sale',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_rw_1',
        title='ASICS Gel-Kayano 30 Hardloopschoenen',
        description='Maximale stabiliteit. GEL-technologie. Voor overpronatie.',
        merchant='Runnersworld',
        merchant_logo='https://logo.clearbit.com/runnersworld.nl',
        original_price=199.99,
        sale_price=149.99,
        discount_percentage=25,
        coupon_code=None,
        affiliate_url='https://www.runnersworld.nl/',
        category='sports',
        image_url='https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=7),
        source='runnersworld',
        source_url='https://www.runnersworld.nl/sale',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    # Food
    Deal(
        id='sample_ah_1',
        title='AH Huismerk Koffiecups 5-pack',
        description='Espresso cups compatible met Nespresso. 50 stuks.',
        merchant='Albert Heijn',
        merchant_logo='https://logo.clearbit.com/ah.nl',
        original_price=12.50,
        sale_price=7.99,
        discount_percentage=36,
        coupon_code=None,
        affiliate_url='https://www.ah.nl/',
        category='food',
        image_url='https://images.unsplash.com/photo-1559496417-e7f25cb247f3?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=7),
        source='ah',
        source_url='https://www.ah.nl/bonus',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_jumbo_1',
        title='Jumbo Biologische Olijfolie Extra Vierge 1L',
        description='Koudgeperst. Italiaanse herkomst. Premium kwaliteit.',
        merchant='Jumbo',
        merchant_logo='https://logo.clearbit.com/jumbo.com',
        original_price=12.99,
        sale_price=8.49,
        discount_percentage=35,
        coupon_code=None,
        affiliate_url='https://www.jumbo.com/',
        category='food',
        image_url='https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=5),
        source='jumbo',
        source_url='https://www.jumbo.com/aanbiedingen',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_lidl_1',
        title='Deluxe Gerookte Zalm 200g',
        description='Noors. Handgesneden. Premium kwaliteit.',
        merchant='Lidl',
        merchant_logo='https://logo.clearbit.com/lidl.nl',
        original_price=6.99,
        sale_price=4.49,
        discount_percentage=36,
        coupon_code=None,
        affiliate_url='https://www.lidl.nl/',
        category='food',
        image_url='https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=4),
        source='lidl',
        source_url='https://www.lidl.nl/aanbiedingen',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_plus_1',
        title='PLUS Huismerk Wasmiddel Pods 50 stuks',
        description='Krachtige reiniging. Frisse geur. Geschikt voor alle machines.',
        merchant='PLUS',
        merchant_logo='https://logo.clearbit.com/plus.nl',
        original_price=14.99,
        sale_price=9.99,
        discount_percentage=33,
        coupon_code=None,
        affiliate_url='https://www.plus.nl/',
        category='food',
        image_url='https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=7),
        source='plus',
        source_url='https://www.plus.nl/aanbiedingen',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
    Deal(
        id='sample_dirk_1',
        title='Coca-Cola Regular 6x1,5L',
        description='Voordeelpak. Originele smaak.',
        merchant='Dirk',
        merchant_logo='https://logo.clearbit.com/dirk.nl',
        original_price=9.54,
        sale_price=5.99,
        discount_percentage=37,
        coupon_code=None,
        affiliate_url='https://www.dirk.nl/',
        category='food',
        image_url='https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400',
        valid_from=datetime.now(),
        valid_until=datetime.now() + timedelta(days=5),
        source='dirk',
        source_url='https://www.dirk.nl/aanbiedingen',
        status=DealStatus.APPROVED,
        created_at=datetime.now(),
        is_active=True
    ),
]

if __name__ == "__main__":
    save_deals(sample_deals)
    print(f"Saved {len(sample_deals)} sample deals")

    # Print summary by category
    from collections import Counter
    cats = Counter(d.category for d in sample_deals)
    for cat, count in sorted(cats.items()):
        print(f"  {cat}: {count} deals")
